"""empty message

Revision ID: f92d1454a57f
Revises: 4e2e86d2b2ab
Create Date: 2026-03-08 18:25:38.654308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92d1454a57f'
down_revision: Union[str, Sequence[str], None] = '4e2e86d2b2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('review_courier_review_id_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'courier', ['courier_review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(op.f('review_courier_review_id_fkey'), 'review', 'profile', ['courier_review_id'], ['id'])
    # ### end Alembic commands ###
